version: '3'
services:
  huort-website-rec__app:
    image: registry.yuniq.agency/my-active-directory/my-active-directory-app-rec:latest
    ports:
      - '10054:3000'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
