version: '3'
services:
  my-active-directory__app:
    image: registry.yuniq.agency/my-active-directory/my-active-directory-app-main:latest
    ports:
      - '10056:3000'
    restart: unless-stopped
    extra_hosts:
      - 'host.docker.internal:host-gateway'
    logging:
      driver: 'json-file'
      options:
        max-size: '50m'
