name: main workflow

on:
  push:
    branches: ['main']
  pull_request:
    branches: ['main']

  workflow_dispatch:

jobs:
  security:
    name: TruffleHog Secrets Scan
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        with:
          fetch-depth: 0
      - name: TruffleHog OSS
        uses: trufflesecurity/trufflehog@main
        with:
          path: ./
          base: ${{ github.event.repository.default_branch }}
          head: HEAD
          extra_args: --debug --only-verified

  code-quality:
    name: Code Quality
    runs-on: ubuntu-latest
    environment: prod
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env
        run: |
          touch .env.local
          echo PORT=3000 >> .env.local
          echo API_URL=${{ vars.API_URL }} >> .env.local

      - name: Install dependencies
        run: npm ci

      - name: Run lint
        run: npm run lint

      - name: Run tests
        run: npm run test -- --passWithNoTests

  run:
    runs-on: ubuntu-latest
    environment: prod

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Create env
        run: |
          touch .env.local
          echo PORT=3000 >> .env.local
          echo API_URL=${{ vars.API_URL }} >> .env.local

      - name: Login to docker
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.REGISTRY_USERNAME }}
          password: ${{ secrets.REGISTRY_KEY }}
          registry: registry.yuniq.agency

      - name: Build the prod docker image
        run: |
          docker build -t main .
          docker tag main:latest registry.yuniq.agency/my-active-directory/my-active-directory-app-main:latest
          docker push registry.yuniq.agency/my-active-directory/my-active-directory-app-main:latest

      - name: Push docker compose
        run: |
          eval $(ssh-agent -s)
          echo "${{ secrets.SSH_KEY }}" | tr -d '\r' | ssh-add - > /dev/null
          mkdir -p ~/.ssh
          chmod 700 ~/.ssh
          ssh-keyscan -t rsa ${{ vars.SSH_HOST }} >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

          ssh -p ${{ vars.SSH_PORT }} ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }} "mkdir -p ~/yuniq/my-active-directory/my-active-directory__app/prod"
          scp -P ${{ vars.SSH_PORT }} docker-compose.yml ${{ vars.SSH_USERNAME }}@${{ vars.SSH_HOST }}:~/yuniq/my-active-directory/my-active-directory__app/prod/docker-compose.yml

      - name: Deploy to prod
        uses: appleboy/ssh-action@master
        with:
          host: ${{ vars.SSH_HOST }}
          username: ${{ vars.SSH_USERNAME }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ vars.SSH_PORT }}
          envs: REGISTRY_USERNAME, REGISTRY_KEY
          script: |
            cd ~/yuniq/my-active-directory/my-active-directory__app/prod
            docker login -u '${{ secrets.REGISTRY_USERNAME }}' -p '${{ secrets.REGISTRY_KEY }}' registry.yuniq.agency
            docker compose -f docker-compose.yml pull
            docker system prune -f
            docker compose -f docker-compose.yml up -d
